### ISSUE TITLE
Provide kmz or kml export of the walk

### ISSUE THREAD

**Issue by AGneissCanadian** [TreeWalks/TreeWalks.github.io#7]
export the kmz file

**Comment by MrCsabaToth** [comment]
Looks like that `kmz` is simple a zipped version of a `kml` file. Here is some info about kml (Keyhole Markup Language): https://en.wikipedia.org/wiki/Keyhole_Markup_Language

**Comment by MrCsabaToth** [comment]
The file is accessible at https://treewalks.github.io/locations.kml
