### ISSUE TITLE
Make a suggestion (issue) button that's easy

### ISSUE THREAD

**Issue by bethweinman** [TreeWalks/TreeWalks.github.io#8]
Filing issues isn't intuitive to non-tech folks; to get helpful requests, it'd be good to have an easier way to submit feedback.

**Comment by MrCsabaToth** [comment]
I'm not sure what would be the best, maybe a Google Form?

**Comment by MrCsabaToth** [comment]
I'm creating a Google Form (or maybe forms, to also have a Spanish version).
