### ISSUE TITLE
Add drought tolerant and CA native status

### ISSUE THREAD

**Issue by bethweinman** [TreeWalks/TreeWalks.github.io#9]
Incorporate drought tolerant and CA native data:  https://docs.google.com/spreadsheets/d/1s8GtXKEdwAt4b4bxgf3uJJ4E3mC7PW5CnBU88yKW6F4/edit#gid=0

**Comment by bethweinman** [comment]
And other fun facts that Seiji has in the additional columns

**Comment by MrCsabaToth** [comment]
The current information I have is from the old tree walk PDFs. We need to figure out how to integrate that exactly. Anything is possible. Just like in the CSV referenced I suggest to separate semantic information (like boolean is it drought tolerant yes/no and boolean is it native yes/no information) into fields. This way we can use them for coloring, or displaying that specific info in a structured format, like I have the latin name, height, width and some more information separately from the free form text description. The more info we have that way the more we can do later, for example filtering the stops by some criteria. The same information can be in the free text as well though, so we don't necessarily have to strip it, it's up to us.

**Comment by MrCsabaToth** [comment]
Instead of California native status we add native region. We also add climate action, pollution, traffic meta data.
